configurationset:
- configuration:
    name: ibm-iam
    endpoint: https://iam.cloud.ibm.com/identity/token
    apikey: STEPZEN_IBM_IAM_APIKEY
- configuration:
    name: watsonx-service
    version: '2024-06-28'
    url: STEPZEN_WATSONXAI_URL
    project_id: STEPZEN_WATSONXAI_PROJECTID
    model_id: "ibm/granite-3-8b-instruct"
